spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: http://localhost:8081/
          predicates:
            - Path=/OrderAPI/api/v1/**
        - id: ProductService
          uri: http://localhost:8083/
          predicates:
            - Path=/ProductAPI/api/v1/**
        - id: PaymentService
          uri: http://localhost:8082/
          predicates:
            - Path=/PaymentAPI/api/v1/**